#!/usr/bin/env python3
"""Rasterise the UI fonts to 4-bit alpha bitmaps in a C header.

Space Grotesk (titles, the decision) and JetBrains Mono (stats), both SIL
Open Font License (assets/fonts/OFL-*.txt). Glyphs are stored cropped to
their ink box with the offsets needed to place them on a shared baseline.

    python tools/make_fonts.py   # writes firmware/ui/fonts.h
"""
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
ASCII = "".join(chr(c) for c in range(32, 127)) + "\u00a3\u00b7"  # + pound sign and middle dot (Latin-1 0xA3, 0xB7 in strings)
BIG = " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:%!?-()"

FONTS = [  # name, file, weight, pixel size, charset
    ("f_small", "JetBrainsMono.ttf", b"Medium", 13, ASCII),
    ("f_body", "SpaceGrotesk.ttf", b"Medium", 18, ASCII),
    ("f_title", "SpaceGrotesk.ttf", b"Bold", 26, ASCII),
    ("f_huge", "SpaceGrotesk.ttf", b"Bold", 46, BIG),
]


def build(name, file, weight, size, chars):
    font = ImageFont.truetype(os.path.join(ROOT, "assets", "fonts", file), size)
    font.set_variation_by_name(weight)
    ascent, descent = font.getmetrics()
    bitmap = bytearray()
    glyphs = []
    for ch in chars:
        adv = int(round(font.getlength(ch)))
        img = Image.new("L", (size * 2, ascent + descent + 4), 0)
        ImageDraw.Draw(img).text((size // 2, 2), ch, font=font, fill=255)
        box = img.getbbox()
        if box is None:
            glyphs.append((ord(ch), 0, 0, 0, 0, adv, len(bitmap)))
            continue
        x0, y0, x1, y1 = box
        w, h = x1 - x0, y1 - y0
        g = img.crop(box)
        px = list(g.getdata())
        off = len(bitmap)
        for i in range(0, len(px), 2):  # two 4-bit alphas per byte, high nibble first
            a = px[i] >> 4
            b = (px[i + 1] >> 4) if i + 1 < len(px) else 0
            bitmap.append((a << 4) | b)
        glyphs.append((ord(ch), w, h, x0 - size // 2, y0 - 2, adv, off))
    lines = [f"static const uint8_t {name}_bits[{len(bitmap)}] = {{"]
    for i in range(0, len(bitmap), 24):
        lines.append("    " + ",".join(str(b) for b in bitmap[i:i + 24]) + ",")
    lines.append("};")
    lines.append(f"static const Glyph {name}_glyphs[{len(glyphs)}] = {{")
    for code, w, h, dx, dy, adv, off in glyphs:
        lines.append(f"    {{{code}, {w}, {h}, {dx}, {dy}, {adv}, {off}}},")
    lines.append("};")
    lines.append(f"static const Font {name} = {{{name}_glyphs, {len(glyphs)}, {name}_bits, "
                 f"{ascent + descent}, {ascent}}};")
    return "\n".join(lines), len(bitmap)


def main():
    out = ["// Generated by tools/make_fonts.py. Fonts: Space Grotesk, JetBrains Mono",
           "// (SIL Open Font License 1.1, assets/fonts/). 4-bit alpha, ink-cropped.",
           "#pragma once", "#include <stdint.h>", '#include "font.h"', ""]
    total = 0
    for spec in FONTS:
        text, n = build(*spec)
        out.append(text)
        out.append("")
        total += n
    path = os.path.join(ROOT, "firmware", "ui", "fonts.h")
    open(path, "w").write("\n".join(out))
    print(f"{path}: {total} bytes of glyph bitmaps")


if __name__ == "__main__":
    main()
